# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a31b930d85ff20d03aea3e0b66799f5a08b7260488b72e271a0d97f21b434fc76bd1adcdd5c917799b630b0f8125c7e79835531fee607e4d60c3fc29b6bb14a

test:
  secret_key_base: f6f33234e6a80d7e048f05071d608b0c2075d4e7c8316173a82f6f9646eb0fa856dcc20f54be417bf8ce7476b7a4208da0d8bb0610b15e625ef4e7e0c0464364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
